### ISSUE TITLE
Job at last day of month

### ISSUE THREAD

**Issue by hiennguyen-agilityio** [ondrejbartas/sidekiq-cron#166] opened 2017-08-01 02:20 UTC
I setup an job run at last day of month.

```
class MonthlyReminderJob
  include Sidekiq::Worker
  sidekiq_options queue: :test, retry: true

  def perform
    timezone = ENV['TIME_ZONE']
    tomorrow = DateTime.now.in_time_zone(timezone).tomorrow

    return unless tomorrow.day == 1

    // TODO
  end
end
```

`sidekiq.rb`
```
jobs = {
  'name' => 'send_monthly_reminder,
  'class' => 'MonthlyReminderJob',
  'cron'  => '0 8 28-31 * * Asia/Kuala_Lumpur',
  'queue' => 'test'
}
```

But it's not working at 31/07. Today (01/08), I visit `sidekiq/cron` and saw `Last enqueued` is `2 days ago`

**Comment by ondrejbartas** [comment] 2017-08-01 11:24
Hi @HienNguyenAsnet pls read documentation for `rufus-scheduler` 
which is used for resolving cron notations in Sidekiq-Cron

this: https://github.com/jmettraux/rufus-scheduler#l-last-day-of-month
part is what you are looking for.

Pls let me know if it works

**Comment by HienNguyenAsnet** [comment] 2017-08-03 03:11
Thank @ondrejbartas. Let me try

**Comment by HienNguyenAsnet** [comment] 2017-08-03 08:56
It's working wrong with timezone

```
Rufus::Scheduler.parse('0 8 L * * Asia/Kuala_Lumpur').next_time
=> 2017-09-01 08:00:00 +0800
```

**Comment by ondrejbartas** [comment] 2017-08-04 14:04
No idea what are you doing but in rails project it looks like this
<img width="1148" alt="screen shot 2017-08-04 at 16 04 19" src="https://user-images.githubusercontent.com/45809/28972079-9bb0de3a-792e-11e7-981b-da5b90ef3e28.png">

**Comment by pedroadame** [comment] 2017-09-01 10:53
hi @ondrejbartas, you set 08:00 at Kuala Lampur which translates to 0:00 UTC, and is showing 08:00 UTC, so no conversion between timezones.

**Comment by ondrejbartas** [comment] 2017-10-04 08:29
@pedroadame which ruby version are you using?

**Comment by pedroadame** [comment] 2017-10-04 09:03
@ondrejbartas Currently is ruby 2.4.0.

**Comment by ondrejbartas** [comment] 2018-02-21 20:25
@pedroadame any news? Sorry for not responding sooner. I have no idea why it works for me and not for you

**Comment by pedroadame** [comment] 2018-02-22 07:12
@ondrejbartas The problem is in your screenshot. 08:00 on Kuala Lampur doesn't match with 08:00 UTC, and that's what is showing in your screenshot here: https://github.com/ondrejbartas/sidekiq-cron/issues/166#issuecomment-320257657

**Comment by HienNguyenAsnet** [comment] 2018-03-01 03:01
The issue doesn't happen often and uniformly
This is Prod server
<img width="522" alt="screen shot 2018-03-01 at 09 33 28" src="https://user-images.githubusercontent.com/5277254/36824215-d2d4ccba-1d33-11e8-8ce3-5091b8dd4351.png">
This is QA server
<img width="519" alt="screen shot 2018-03-01 at 09 33 38" src="https://user-images.githubusercontent.com/5277254/36824250-ef148d7a-1d33-11e8-8d80-197e452a21ae.png">

**Closed** 2022-04-14 07:46 UTC
Labels: wontfix
