### ISSUE TITLE
Do not enqueue if job is in queue or is currently processing

### ISSUE THREAD

**Issue by ondrejbartas** [ondrejbartas/sidekiq-cron#55] opened 2015-07-29 17:11 UTC
@matthuhiggins has in his fork very interesting idea.

(https://github.com/matthuhiggins/sidekiq-cron/tree/singleton-cron)

This enables to say, hey I do not need to add new job if job is already in queue or currently processing.

It is remembering last enqueued job id and then when time comes and new job should be enqueued it is looking to queues and currently working sidekiq workers if it is there.

**Comment by ondrejbartas** [comment] 2015-07-29 17:12
Do you like this feature?

**Comment by matthuhiggins** [comment] 2015-07-29 17:18
I've been running a branch of it for our own project. I was a bit nervous about any race conditions, etc, but I do not think there are any.

I was going to talk to you about it once I fixed up the tests. I'd be eager to work on this more if you like this idea.

**Comment by ondrejbartas** [comment] 2015-07-30 16:14
There are no race conditions as I was thinking about this and saw your code.

But still thinking why do you need this.

Can you explain me what is your goal by this?

**Comment by matthuhiggins** [comment] 2015-07-30 16:23
This is needed whenever a job's schedule is more frequent than the time it takes for a job to run. It is a classic problem from normal cron (http://serverfault.com/questions/82857/prevent-duplicate-cron-jobs-running).

An example in our case: a job runs every 15 minutes to check for a certain file on S3. When that file appears, the job takes about an hour to run. Turning the job's frequency to a time such as every 2 hours is not going to work, since we want to notice the file as quickly as possible.

This is a trivial case, and I could of course have this specific job manually figure out if it is already running with a special solution. However, since the problem is common, that is why I wanted to put it into sidekiq cron.

**Comment by antulik** [comment] 2015-08-02 07:06
+1 for such feature. We have very similar use case, when we need to run job frequently but it's possible that job will take longer than that frequency. 

From past experience in other projects we also had such need and used system cron with lock file.

**Comment by hgani** [comment] 2015-09-21 09:50
+1 

I need this in both my personal project and my project at work.

**Comment by antulik** [comment] 2015-10-08 23:59
found this https://github.com/krasnoukhov/sidekiq-middleware but haven't tried it yet. Can anybody confirm if it works with sidekiq-cron?

**Comment by dim** [comment] 2015-10-15 14:14
:+1:

**Comment by caiosba** [comment] 2015-10-28 19:48
This works with Sidekiq Cron: https://github.com/meedan/sidekiq-uniq

**Comment by dolzenko** [comment] 2015-10-29 09:33
@caiosba Thanks, just not sure this fully covers the requirements in this ticket, namely it only checks if the job is in the queue and doesn't check for currently processing jobs?

**Comment by caiosba** [comment] 2015-10-29 16:39
Yeah, you're right... let me fix that...

**Comment by barkerja** [comment] 2015-10-29 18:48
Couldn't you simply use Redis to act as a global semaphore? Run a lock check in the method executing the job, if the lock exists, simply return without executing the job. You of course would want a reasonable timeout in the case the job fails and is unable to release the lock.

**Comment by caiosba** [comment] 2015-10-29 18:52
Yeah that's what I'm doing now... it also leads to better performance

**Comment by caiosba** [comment] 2015-10-29 22:03
Hey guys, please check the latest version (0.6.0) from https://github.com/meedan/sidekiq-uniq.

Now it doesn't allow a job to be enqueued if it's already in the queue or being processed.

It does so by keeping in Redis the information about each job's status, where a job is identified by its class and arguments. Possible statuses are: enqueued, running and completed. In case a job fails and is unable to release the lock, all status keys expire (by using Redis' EXPIRE command) after some time (which can be defined by Sidekiq::Uniq::Status.expiration = <time in seconds>).

**Comment by caiosba** [comment] 2015-11-05 19:07
I've using https://github.com/meedan/sidekiq-uniq for one week now and it solved this issue for me. If other users agree, we could close this issue?

**Comment by antulik** [comment] 2015-11-06 04:03
another gem https://github.com/mhenrixon/sidekiq-unique-jobs which is more popular and provides better configuration

**Closed** 2017-04-18 09:12 UTC
