### ISSUE TITLE
Does not work. Jobs do not start automatically

### ISSUE THREAD

**Issue by galievruslan** [ondrejbartas/sidekiq-cron#325] opened 2022-04-13 09:12 UTC
Hello
I use
Rails 6.1.4
Redis 6.2.6
Sidekiq v6.4.1
Sidekiq-cron 1.3.0

Tasks are launched without problems from Web UI. But they don't start automatically. There are no errors in the logs.
I create job :
`Sidekiq::Cron::Job.create(name: 'Send report', cron: '*/5 * * * *', class: 'VihoCms::Reports::SummaryReportJob', args: [ENV['REPORT_EMAIL'], 12])`
and like this
```
array = [
      {
        'name'  => 'Send report'',
        'class' => 'VihoCms::Reports::SummaryDonationsReportJob',
        'cron'  => '0/5 * * * *',
        'args'  => [[ENV['REPORT_EMAIL'], 12]
      }
]
Sidekiq::Cron::Job.load_from_array! array
```
But it doesn't affect. Sidekiq process works correctly. And I will repeat the tasks are launched and work correctly when they are started from Web UI.

**Comment by jsantos** [comment] 2022-04-18 10:33
How often are you running this set of commands?

I see you're using the bang (!) method, and from the [docs](https://github.com/ondrejbartas/sidekiq-cron#adding-cron-job):

> Bang-suffixed methods will remove jobs that are not present in the given hash/array, update jobs that have the same names, and create new ones when the names are previously unknown.

**Comment by galievruslan** [comment] 2022-04-20 06:46
> How often are you running this set of commands?
> 
> I see you're using the bang (!) method, and from the [docs](https://github.com/ondrejbartas/sidekiq-cron#adding-cron-job):
> 
> > Bang-suffixed methods will remove jobs that are not present in the given hash/array, update jobs that have the same names, and create new ones when the names are previously unknown.

No i run this command only one time. I know  I know that restarting deletes jobs with the same name. On web UI admin I see jobs, and I can run this jobs manually, but they don't start automatically

**Comment by jsantos** [comment] 2022-04-20 06:54
> No i run this command only one time. I know I know that restarting deletes jobs with the same name. On web UI admin I see jobs, and I can run this jobs manually, but they don't start automatically

What's your use case exactly? I usually load the jobs from a YML file and seems to work fine for me.

**Comment by galievruslan** [comment] 2022-04-20 13:30
I checked two variants 
`Sidekiq::Cron::Job.create(name: 'Send report', cron: '*/5 * * * *', class: 'VihoCms::Reports::SummaryReportJob', args: [ENV['REPORT_EMAIL'], 12])`
and like this

```
array = [
      {
        'name'  => 'Send report'',
        'class' => 'VihoCms::Reports::SummaryDonationsReportJob',
        'cron'  => '0/5 * * * *',
        'args'  => [[ENV['REPORT_EMAIL'], 12]
      }
]
Sidekiq::Cron::Job.load_from_array! array
```
Both variants are create jobs, I see jobs on Web UI. I can run jobs manually, but automatically they don't run.

**Comment by ivelq3** [comment] 2022-05-16 15:02
Faced the same problem

cron = '0/5 * * * *'

Fugit.do_parse_cron(cron)
@cron_s=nil,
@hours=nil,
@minutes=[0],
@monthdays=nil,
@months=nil,
@original="0/5 * * * *",
@seconds=[0],

Fugit::Nat.parse('every 5 minutes').to_cron_s
=> "0,5,10,15,20,25,30,35,40,45,50,55 * * * *"

cron = "0,5,10,15,20,25,30,35,40,45,50,55 * * * *"

Fugit.do_parse_cron(cron)
@cron_s=nil,
@hours=nil,
@minutes=[0, 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55],
@monthdays=nil,
@months=nil,
@original="0,5,10,15,20,25,30,35,40,45,50,55 * * * *",
@seconds=[0],

use Fugit::Nat.parse().to_cron_s to get a valid cron

**Comment by dylan-zepto** [comment] 2022-07-11 00:43
@galievruslan We are having the same issues here, have you found a fix yet since April? We found that being explicit (i.e. status: enabled) solves the issue

**Comment by markets** [comment] 2022-08-16 19:42
To start running jobs, don't forget to start the Sidekiq workers: https://github.com/ondrejbartas/sidekiq-cron#how-to-start-scheduling.

**Comment by markets** [comment] 2022-09-16 17:19
Hello 👋🏼 going to close this one, as no new info or some reproducible scenario was provided...

Since v1.6 we support autoloading the `config/schedule.yml` and it just works 👌🏼. To start scheduling jobs, don't forget to start the Sidekiq workers.

On the other side, we have a bunch of related tests ensuring this functionality is working well:

https://github.com/ondrejbartas/sidekiq-cron/blob/7acecdea4ef8b17b27ae635fc8698704aa1a0773/test/unit/job_test.rb#L1155 

So we can't do more without a failing test/scenario. Thanks!

**Closed by markets** 2022-09-16 17:19 UTC
